library(dplyr)
library(tidyverse)
library(scales)
library(ggplot2)
library(choroplethr)
library(choroplethrMaps)
library(openintro)
library("readxl")
Stud=read_excel("D:/DataAnalytic/Python/R Programming/EDA Student Covid Response/students_covid_response.xlsx")
print(Stud)
print(View(Stud))
print(head(Stud))
print(tail(Stud))
head(Stud,3)
print(summary(Stud))
print(str(Stud))
print(glimpse(Stud))
